FORMAT: 1A
HOST: http://52.31.72.139/

# vw2-api

The VW2-API provides a represenation of data handling for [ViewWorld](http://viewworld.net).
We follow the RESTful principles, so the API is stateless and http methods 
and response codes are used whenever possible.

## Sessions [/sessions]

### sessions#create [POST]
Before using the API you have to authenticate yourself with valid ```login``` (name or email) and ```password```.
JSON representation of given user with valid authentication token is returned
if everything goes well. Each subsequent request to different API endpoints has to have
```Authorization``` header with valid token as a value.
Please note that ```token``` in this and all other endpoints is only an example and for
working with the API you have to generate your own valid ```token```.

+ Request (application/json)

        {
            "login": "testuser",
            "password": "testpassword"
        }
        
+ Response 201 (application/json; charset=utf-8)

    + Body
    
            {
                "id": 1,
                "token": "3KeAPOuxtIFCMweJB7qLVA",
                "email": "testuser@viewworld.net",
                "first_name": "Test",
                "last_name": "User"
            }
            
### sessions#destroy [DELETE]
To log out it's necessary to delete current authentication token through this endpoint.

+ Request
    + Headers
    
            Authentication: 3KeAPOuxtIFCMweJB7qLVA

+ Response 204

## Forms Collection [/forms]

### forms#index [GET]
Collection of all availible forms scoped to currently signed in user.
So only forms associated to same Organisation as a User are listed.
> Accessible by: 
> ```Sysadmin```,
> ```Admin```

+ Request
    + Headers
    
            Authentication: 3KeAPOuxtIFCMweJB7qLVA

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "id":647,
                "name":"International Mobilization and Preparation for ACTion",
                "data":[
                    {
                        "id":1,
                        "title":"1. Please indicate whether you did not start, partially completed, or fully completed the course:",
                        "type":"select"
                    },
                    {
                        "id":2,
                        "title":"2. In general, how would you rate your experience of the course?",
                        "type":"select"
                    },
                    {
                        "id":3,
                        "title":"If you answered \"below average\" or \"poor\" then please explain why",
                        "type":"text"
                    },
                    {
                        "id":4,
                        "title":"3. Overall, were the explanations of the different topics clear?",
                        "type":"select"
                    },
                    {
                        "id":5,
                        "title":"If you answered \"disagree\" or \"strongly disagree\" then please explain why",
                        "type":"text"
                    },
                    {
                        "id":6,
                        "title":"4. Did the different interactive exercises help you to understand the related topic?",
                        "type":"select"
                    },
                    {
                        "id":7,
                        "title":"If you answered \"disagree\" or \"strongly disagree\" then please explain why",
                        "type":"text"
                    },
                    {
                        "id":8,
                        "title":"5. Did you learn what you expected about the subject matter?",
                        "type":"select"
                    },
                    {
                        "id":9,
                        "title":"If you answered \"disagree\" or \"strongly disagree\" then please explain why",
                        "type":"text"
                    },
                    {
                        "id":10,
                        "title":"6. Do you feel that what you have learned will contribute to improving your own professional work?",
                        "type":"select"
                    },
                    {
                        "id":11,
                        "title":"If you answered \"disagree\" or \"strongly disagree\" then please explain why",
                        "type":"text"
                    },
                    {
                        "id":12,
                        "title":"7. Do you feel you are now better able to [add learning objective]?",
                        "type":"select"
                    },
                    {
                        "id":13,
                        "title":"If you answered \"disagree\" or \"strongly disagree\" then please explain why",
                        "type":"text"
                    },
                    {
                        "id":14,
                        "title":"8. Would you recommend this course to your colleagues?",
                        "type":"select"
                    },
                    {
                        "id":15,
                        "title":"If you answered \"disagree\" or \"strongly disagree\" then please explain why",
                        "type":"text"
                    },
                    {
                        "id":16,
                        "title":"9. Did you have any technical or other problems to access, start or follow the course?",
                        "type":"select"
                    },
                    {
                        "id":17,
                        "title":"If you answered \"yes\" then please explain why. If you could not start or complete the course for other reasons, please note that here also.",
                        "type":"text"
                    },
                    {
                        "id":18,
                        "title":"User",
                        "type":"metadata"
                    },
                    {
                        "id":19,
                        "title":"time",
                        "type":"metadata"
                    }
                ]
            },
            {
                "id":1058,
                "name":"Instructor data, Instructor Seminar, Citluk/BiH, 18-21.6.2013 06-24-2013 09:42:04",
                "data":[
                    {
                        "id":1,
                        "title":"Place of residence",
                        "type":"select"
                    },
                    {
                        "id":2,
                        "title":"Date",
                        "type":"date_time"
                    },
                    {
                        "id":3,
                        "title":"Number of participants",
                        "type":"numeric"
                    },
                    {
                        "id":4,
                        "title":"Women",
                        "type":"numeric"
                    },
                    {
                        "id":5,
                        "title":"Male",
                        "type":"numeric"
                    },
                    {
                        "id":6,
                        "title":"",
                        "type":"explanation_text"
                    },
                    {
                        "id":7,
                        "title":"Bosniak",
                        "type":"numeric"
                    },
                    {
                        "id":8,
                        "title":"Croat",
                        "type":"numeric"
                    },
                    {
                        "id":9,
                        "title":"Serb",
                        "type":"numeric"
                    },
                    {
                        "id":10,
                        "title":"Montenegrian",
                        "type":"numeric"
                    },
                    {
                        "id":11,
                        "title":"Macedonian",
                        "type":"numeric"
                    },
                    {
                        "id":12,
                        "title":"Albanian",
                        "type":"numeric"
                    },
                    {
                        "id":13,
                        "title":"Roma",
                        "type":"numeric"
                    },
                    {
                        "id":14,
                        "title":"Other",
                        "type":"numeric"
                    },
                    {
                        "id":15,
                        "title":"If other please specify",
                        "type":"text"
                    },
                    {
                        "id":16,
                        "title":"",
                        "type":"page_break"
                    },
                    {
                        "id":17,
                        "title":"",
                        "type":"explanation_text"
                    },
                    {
                        "id":18,
                        "title":"Under 20 years",
                        "type":"numeric"
                    },
                    {
                        "id":19,
                        "title":"21-30 years",
                        "type":"numeric"
                    },
                    {
                        "id":20,
                        "title":"31-50 years",
                        "type":"numeric"
                    },
                    {
                        "id":21,
                        "title":"Over 50 years",
                        "type":"numeric"
                    },
                    {
                        "id":22,
                        "title":"",
                        "type":"explanation_text"
                    },
                    {
                        "id":23,
                        "title":"Work with pre-school children",
                        "type":"numeric"
                    },
                    {
                        "id":24,
                        "title":"Teacher in primary school",
                        "type":"numeric"
                    },
                    {
                        "id":25,
                        "title":"School related job (not teacher)",
                        "type":"numeric"
                    },
                    {
                        "id":26,
                        "title":"Sport coach",
                        "type":"numeric"
                    },
                    {
                        "id":27,
                        "title":"Other sport related job (not coach)",
                        "type":"numeric"
                    },
                    {
                        "id":28,
                        "title":"Social worker",
                        "type":"numeric"
                    },
                    {
                        "id":29,
                        "title":"Police or similar",
                        "type":"numeric"
                    },
                    {
                        "id":30,
                        "title":"Other professions",
                        "type":"numeric"
                    },
                    {
                        "id":31,
                        "title":"",
                        "type":"page_break"
                    },
                    {
                        "id":32,
                        "title":"",
                        "type":"explanation_text"
                    },
                    {
                        "id":33,
                        "title":"Less than 1 years",
                        "type":"numeric"
                    },
                    {
                        "id":34,
                        "title":"1-3 years",
                        "type":"numeric"
                    },
                    {
                        "id":35,
                        "title":"4-6 years",
                        "type":"numeric"
                    },
                    {
                        "id":36,
                        "title":"7-10 years",
                        "type":"numeric"
                    },
                    {
                        "id":37,
                        "title":"More",
                        "type":"numeric"
                    },
                    {
                        "id":38,
                        "title":"coll",
                        "type":"group"
                    },
                    {
                        "id":39,
                        "title":"etnic",
                        "type":"group"
                    }
                ]
            }
        ]
        
### forms#create [POST]
You may create your own form using this endpoint.
Form has to be posted as valid JSON with all required data fields.
Returns created form with status ```201```.

+ Request (application/json)
    + Headers
    
            Authentication: 3KeAPOuxtIFCMweJB7qLVA
            
    + Body

            {
                "name":"Demo Species Observations",
                "groups":[
                    1,
                    2,
                    3
                ],
                "active":true,
                "data":[
                    {
                        "id":1,
                        "hint":{
                            "en":"name of species"
                        },
                        "type":"text",
                        "items":{
                        },
                        "title":{
                            "en":"What species did you see?"
                        },
                        "editable":true,
                        "required":true
                    },
                    {
                        "id":2,
                        "hint":{
                            "en":"name of species"
                        },
                        "type":"text",
                        "items":{
                        },
                        "title":{
                            "en":"What species did you see?"
                        },
                        "editable":true,
                        "required":true
                    }
                ],
                "order":[
                    2,
                    1
                ]
            }

+ Response 201 (application/json; charset=utf-8)

            {
                "id":2315,
                "name":"Demo Species Observations",
                "active":true,
                "locked":false,
                "verification":{
                    "required":false,
                    "default":"verified"
                },
                "data":[
                    {
                        "id":1,
                        "hint":{
                            "en":"name of species"
                        },
                        "type":"text",
                        "items":{
                        },
                        "title":{
                            "en":"What species did you see?"
                        },
                        "editable":true,
                        "required":true
                    },
                    {
                        "id":2,
                        "hint":{
                            "en":"name of species"
                        },
                        "type":"text",
                        "items":{
                        },
                        "title":{
                            "en":"What species did you see?"
                        },
                        "editable":true,
                        "required":true
                    }
                ],
                "groups":[
                    {
                        "id":8,
                        "parent_id":1,
                        "name":"Demo HQ"
                    },
                    {
                        "id":1838,
                        "parent_id":8,
                        "name":"qweqwe"
                    },
                    {
                        "id":1928,
                        "parent_id":8,
                        "name":"Collection of animals"
                    },
                    {
                        "id":1929,
                        "parent_id":8,
                        "name":"Niels DEMO group"
                    },
                    {
                        "id":1927,
                        "parent_id":8,
                        "name":"Map constructor presentation"
                    },
                    {
                        "id":142,
                        "parent_id":8,
                        "name":"Country Office"
                    },
                    {
                        "id":1364,
                        "parent_id":8,
                        "name":"Business"
                    },
                    {
                        "id":1815,
                        "parent_id":8,
                        "name":"dev-test-organisation-1.0.0"
                    },
                    {
                        "id":2015,
                        "parent_id":8,
                        "name":"Well inspectors"
                    },
                    {
                        "id":2035,
                        "parent_id":8,
                        "name":"Well inspectors..."
                    },
                    {
                        "id":2016,
                        "parent_id":8,
                        "name":"Vllage Capacity Test"
                    },
                    {
                        "id":1099,
                        "parent_id":142,
                        "name":"Uganda"
                    },
                    {
                        "id":1392,
                        "parent_id":1203,
                        "name":"Kunde"
                    },
                    {
                        "id":1363,
                        "parent_id":1364,
                        "name":"Distribution"
                    },
                    {
                        "id":1203,
                        "parent_id":1364,
                        "name":"Håndværker"
                    },
                    {
                        "id":1818,
                        "parent_id":1815,
                        "name":"dev-organisation-group-1.1.1"
                    },
                    {
                        "id":1817,
                        "parent_id":1815,
                        "name":"dev-test-organisation-1.1.0"
                    },
                    {
                        "id":1819,
                        "parent_id":1815,
                        "name":"dev-organisation-group-1.1.2"
                    },
                    {
                        "id":1822,
                        "parent_id":1817,
                        "name":"dev-test-organisation-1.2.2"
                    },
                    {
                        "id":1821,
                        "parent_id":1817,
                        "name":"dev-test-organisation-1.2.1"
                    }
                ]
            }

## Form [/forms/{form_id}]

+ Parameters
    + form_id:12 (number) - ID of requested form.

### forms#show [GET]
JSON representation of requested form. Objects in data array are ordered according to ```order``` field.
```order``` field is accesible only during ```POST``` and ```PATCH```.
All members of ```groups``` array has optional ```associated``` value.
For users form is visible only if  it has set ```associated: true``` to the same Group as given User.

+ Request
    + Headers
    
            Authentication: 3KeAPOuxtIFCMweJB7qLVA

+ Response 200 (application/json; charset=utf-8)

        {
            "id":647,
            "name":"International Mobilization and Preparation for ACTion",
            "locked":false,
            "verification":{
                "required":null,
                "default":"submitted"
            },
            "data":[
                {
                    "id":1,
                    "hint":"",
                    "type":"select",
                    "items":[
                        {
                            "type":"text",
                            "label":"Did not start the course",
                            "value":"Did not start the course",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Partially completed the course",
                            "value":"Partially completed the course",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Fully completed the course",
                            "value":"Fully completed the course",
                            "default":false
                        }
                    ],
                    "title":"1. Please indicate whether you did not start, partially completed, or fully completed the course:",
                    "editable":true,
                    "required":true,
                    "includedInFeed":false
                },
                {
                    "id":2,
                    "hint":"",
                    "type":"select",
                    "items":[
                        {
                            "type":"text",
                            "label":"Excellent",
                            "value":"5",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Above average",
                            "value":"4",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Average",
                            "value":"3",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Below average",
                            "value":"2",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Poor",
                            "value":"1",
                            "default":false
                        }
                    ],
                    "title":"2. In general, how would you rate your experience of the course?",
                    "editable":true,
                    "required":false
                },
                {
                    "id":3,
                    "hint":"",
                    "type":"text",
                    "items":{
                        "required":false
                    },
                    "title":"If you answered \"below average\" or \"poor\" then please explain why",
                    "editable":true,
                    "required":false
                },
                {
                    "id":4,
                    "hint":"",
                    "type":"select",
                    "items":[
                        {
                            "type":"text",
                            "label":"Strongly agree",
                            "value":"5",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Agree",
                            "value":"4",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Neither agree nor disagree",
                            "value":"3",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Disagree",
                            "value":"2",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Strongly disagree",
                            "value":"1",
                            "default":false
                        }
                    ],
                    "title":"3. Overall, were the explanations of the different topics clear?",
                    "editable":true,
                    "required":false
                },
                {
                    "id":5,
                    "hint":"",
                    "type":"text",
                    "items":{
                        "required":false
                    },
                    "title":"If you answered \"disagree\" or \"strongly disagree\" then please explain why",
                    "editable":true,
                    "required":false
                },
                {
                    "id":6,
                    "hint":"",
                    "type":"select",
                    "items":[
                        {
                            "type":"text",
                            "label":"Strongly agree",
                            "value":"5",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Agree",
                            "value":"4",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Neither agree nor disagree",
                            "value":"3",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Disagree",
                            "value":"2",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Strongly disagree",
                            "value":"1",
                            "default":false
                        }
                    ],
                    "title":"4. Did the different interactive exercises help you to understand the related topic?",
                    "editable":true,
                    "required":false
                },
                {
                    "id":7,
                    "hint":"",
                    "type":"text",
                    "items":{
                        "required":false
                    },
                    "title":"If you answered \"disagree\" or \"strongly disagree\" then please explain why",
                    "editable":true,
                    "required":false
                },
                {
                    "id":8,
                    "hint":"",
                    "type":"select",
                    "items":[
                        {
                            "type":"text",
                            "label":"Strongly agree",
                            "value":"5",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Agree",
                            "value":"4",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Neither agree nor disagree",
                            "value":"3",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Disagree",
                            "value":"2",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Strongly disagree",
                            "value":"1",
                            "default":false
                        }
                    ],
                    "title":"5. Did you learn what you expected about the subject matter?",
                    "editable":true,
                    "required":false
                },
                {
                    "id":9,
                    "hint":"",
                    "type":"text",
                    "items":{
                        "required":false
                    },
                    "title":"If you answered \"disagree\" or \"strongly disagree\" then please explain why",
                    "editable":true,
                    "required":false
                },
                {
                    "id":10,
                    "hint":"",
                    "type":"select",
                    "items":[
                        {
                            "type":"text",
                            "label":"Strongly agree",
                            "value":"5",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Agree",
                            "value":"4",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Neither agree nor disagree",
                            "value":"3",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Disagree",
                            "value":"2",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Strongly disagree",
                            "value":"1",
                            "default":false
                        }
                    ],
                    "title":"6. Do you feel that what you have learned will contribute to improving your own professional work?",
                    "editable":true,
                    "required":false
                },
                {
                    "id":11,
                    "hint":"",
                    "type":"text",
                    "items":{
                        "required":false
                    },
                    "title":"If you answered \"disagree\" or \"strongly disagree\" then please explain why",
                    "editable":true,
                    "required":false
                },
                {
                    "id":12,
                    "hint":"",
                    "type":"select",
                    "items":[
                        {
                            "type":"text",
                            "label":"Strongly agree",
                            "value":"5",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Agree",
                            "value":"4",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Neither agree nor disagree",
                            "value":"3",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Disagree",
                            "value":"2",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Strongly disagree",
                            "value":"1",
                            "default":false
                        }
                    ],
                    "title":"7. Do you feel you are now better able to [add learning objective]?",
                    "editable":true,
                    "required":false
                },
                {
                    "id":13,
                    "hint":"",
                    "type":"text",
                    "items":{
                        "required":false
                    },
                    "title":"If you answered \"disagree\" or \"strongly disagree\" then please explain why",
                    "editable":true,
                    "required":false
                },
                {
                    "id":14,
                    "hint":"",
                    "type":"select",
                    "items":[
                        {
                            "type":"text",
                            "label":"Strongly agree",
                            "value":"5",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Agree",
                            "value":"4",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Neither agree nor disagree",
                            "value":"3",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Disagree",
                            "value":"2",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"Strongly disagree",
                            "value":"1",
                            "default":false
                        }
                    ],
                    "title":"8. Would you recommend this course to your colleagues?",
                    "editable":true,
                    "required":false
                },
                {
                    "id":15,
                    "hint":"",
                    "type":"text",
                    "items":{
                        "required":false
                    },
                    "title":"If you answered \"disagree\" or \"strongly disagree\" then please explain why",
                    "editable":true,
                    "required":false
                },
                {
                    "id":16,
                    "hint":"",
                    "type":"select",
                    "items":[
                        {
                            "type":"text",
                            "label":"Yes",
                            "value":"Yes",
                            "default":false
                        },
                        {
                            "type":"text",
                            "label":"No",
                            "value":"No",
                            "default":false
                        }
                    ],
                    "title":"9. Did you have any technical or other problems to access, start or follow the course?",
                    "editable":true,
                    "required":false
                },
                {
                    "id":17,
                    "hint":"",
                    "type":"text",
                    "items":{
                        "required":false
                    },
                    "title":"If you answered \"yes\" then please explain why. If you could not start or complete the course for other reasons, please note that here also.",
                    "editable":true,
                    "required":false
                },
                {
                    "id":18,
                    "hint":"",
                    "type":"metadata",
                    "items":{
                        "required":true
                    },
                    "title":"User",
                    "editable":false,
                    "required":true,
                    "includedInFeed":true
                },
                {
                    "id":19,
                    "hint":"",
                    "type":"metadata",
                    "items":{
                        "required":true
                    },
                    "title":"time",
                    "editable":false,
                    "required":true
                }
            ],
            "groups":[
                {
                    "id":8,
                    "parent_id":1,
                    "name":"Demo HQ"
                },
                {
                    "id":1838,
                    "parent_id":8,
                    "name":"qweqwe"
                },
                {
                    "id":1928,
                    "parent_id":8,
                    "name":"Collection of animals"
                },
                {
                    "id":1929,
                    "parent_id":8,
                    "name":"Niels DEMO group"
                },
                {
                    "id":1927,
                    "parent_id":8,
                    "name":"Map constructor presentation"
                },
                {
                    "id":142,
                    "parent_id":8,
                    "name":"Country Office"
                },
                {
                    "id":1364,
                    "parent_id":8,
                    "name":"Business"
                },
                {
                    "id":1815,
                    "parent_id":8,
                    "name":"dev-test-organisation-1.0.0"
                },
                {
                    "id":2015,
                    "parent_id":8,
                    "name":"Well inspectors"
                },
                {
                    "id":2035,
                    "parent_id":8,
                    "name":"Well inspectors..."
                },
                {
                    "id":2016,
                    "parent_id":8,
                    "name":"Vllage Capacity Test"
                },
                {
                    "id":1099,
                    "parent_id":142,
                    "name":"Uganda"
                },
                {
                    "id":1392,
                    "parent_id":1203,
                    "name":"Kunde"
                },
                {
                    "id":1363,
                    "parent_id":1364,
                    "name":"Distribution"
                },
                {
                    "id":1203,
                    "parent_id":1364,
                    "name":"Håndværker"
                },
                {
                    "id":1818,
                    "parent_id":1815,
                    "name":"dev-organisation-group-1.1.1"
                },
                {
                    "id":1817,
                    "parent_id":1815,
                    "name":"dev-test-organisation-1.1.0"
                },
                {
                    "id":1819,
                    "parent_id":1815,
                    "name":"dev-organisation-group-1.1.2"
                },
                {
                    "id":1822,
                    "parent_id":1817,
                    "name":"dev-test-organisation-1.2.2"
                },
                {
                    "id":1821,
                    "parent_id":1817,
                    "name":"dev-test-organisation-1.2.1"
                }
            ]
        }
        

## Reports [/forms/{form_id}/reports]

+ Parameters
    + form_id:12 (number) - ID of form associated with report.
    
### reports#index [GET]

+ Request
    + Headers
    
            Authentication: 3KeAPOuxtIFCMweJB7qLVA

+ Response 200 (application/json; charset=utf-8)


### reports#create [POST]

+ Request (application/json)
    + Headers
    
            Authentication: 3KeAPOuxtIFCMweJB7qLVA
            
    + Body
    
            {
                "data": [
                    {"1": "tiger"},
                    {"2": "lion"}
                ]
            }

+ Response 201 (application/json; charset=utf-8)

            {
                "id": 2,
                "form_id": 2315,
                "data": [
                    {
                        "1": "tiger"
                    },
                    {
                        "2": "lion"
                    }
                ]
            }

## Report [/forms/{form_id}/reports/{report_id}]

+ Parameters
    + form_id:12 (number) - ID of form associated with report.
    + report_id:1 (number) - ID of requested report.
    
### reports#show [GET]

+ Request
    + Headers
    
            Authentication: 3KeAPOuxtIFCMweJB7qLVA

+ Response 200 (application/json; charset=utf-8)

            {
                "id":15,
                "form_id":2318,
                "data":[
                    {
                        "id":1,
                        "hint": "name of species",
                        "type":"text",
                        "report":"tiger",
                        "title": "What species did you see?",
                        "editable":true,
                        "required":true
                    },
                    {
                        "id":2,
                        "hint": "name of species",
                        "type":"text",
                        "report":"true",
                        "title": "What species did you see?",
                        "editable":true,
                        "required":true
                    },
                    {
                        "id":3,
                        "hint": "fileupload",
                        "type":"media",
                        "report":{
                            "name":"fp.jpg",
                            "content_type":"image/jpeg",
                            "url":"/files/16/original/fp.jpg?1455108639"
                        },
                        "title": "upload file?",
                        "editable":true,
                        "required":true
                    }
                ]
            }
            
## ReportFiles [/forms/{form_id}/report_files]

+ Parameters
    + form_id:12 (number) - ID of form associated with report.
    

### report_files#create [POST]

+ Request (application/json)
    + Headers
    
            Authentication: 3KeAPOuxtIFCMweJB7qLVA
            
    + Body
    
            {
                "data": [
                    {"1": "tiger"},
                    {"2": "lion"}
                ]
            }

+ Response 200 (application/json; charset=utf-8)

## Organisations [/organisations]

### organisations#index [GET]

+ Request (application/json)
    + Headers

            Authentication: 3KeAPOuxtIFCMweJB7qLVA
            
+ Response 200 (application/json; charset=utf-8)

        [
            {
                "id":619,
                "name":"adipo"
            },
            {
                "id":648,
                "name":"Global fund"
            },
            {
                "id":653,
                "name":"EnviClean"
            },
            {
                "id":657,
                "name":"UNDP"
            },
            {
                "id":661,
                "name":"adwordstest"
            },
            {
                "id":8,
                "name":"Sofies"
            },
            {
                "id":60,
                "name":"CRS"
            }
        ]

## Organisation [/organisations/{organisation_id}]

+ Parameters
    + organisation_id:3 (number) - ID of organisation


### organisations#show [GET]

+ Request (application/json)
    + Headers

            Authentication: 3KeAPOuxtIFCMweJB7qLVA
            
+ Response 200 (application/json; charset=utf-8)

        {
            "id":3,
            "name":"Demo HQ",
            "groups":[
                {
                    "id":8,
                    "parent_id":1,
                    "name":"Demo HQ"
                },
                {
                    "id":2016,
                    "parent_id":8,
                    "name":"Vllage Capacity Test"
                },
                {
                    "id":1099,
                    "parent_id":142,
                    "name":"Uganda"
                },
                {
                    "id":1392,
                    "parent_id":1203,
                    "name":"Kunde"
                },
                {
                    "id":1821,
                    "parent_id":1817,
                    "name":"dev-test-organisation-1.2.1"
                }
            ],
            "users":[
                {
                    "id":2176,
                    "token":null,
                    "email":"tomas.koutsky@gmail.com",
                    "first_name":"tomas",
                    "last_name":"koutsky"
                },
                {
                    "id":469,
                    "token":null,
                    "email":"kathalystconsultant@gmail.com",
                    "first_name":"kathrine",
                    "last_name":"Alexandrowiz"
                },
                {
                    "id":56,
                    "token":null,
                    "email":"ivnsnk.cz@gmail.com",
                    "first_name":"Admin",
                    "last_name":"demo"
                },
                {
                    "id":1228,
                    "token":null,
                    "email":"tss@stevnss.com",
                    "first_name":"Thor",
                    "last_name":"Stevnss"
                },
                {
                    "id":1714,
                    "token":null,
                    "email":"rf@fairpeople.com",
                    "first_name":"Rasmus",
                    "last_name":"Feilberg"
                },
                {
                    "id":1272,
                    "token":null,
                    "email":"cthing@mail.dk",
                    "first_name":"Christian ",
                    "last_name":"Thing"
                },
                {
                    "id":1229,
                    "token":null,
                    "email":"littelesun@viewworld.dk",
                    "first_name":"Little",
                    "last_name":"Sun"
                }
            ]
        }

## Subscribtion [/organisations/{organisation_id}/subscribtion]

+ Parameters
    + organisation_id:3 (number) - ID of organisation
    

### subscribtions#show [GET]

+ Request (application/json)
    + Headers

            Authentication: 3KeAPOuxtIFCMweJB7qLVA

+ Response 200 (application/json; charset=utf-8)

        {
            "id":"54468038",
            "email":"ivnsnk.cz@gmail.com",
            "first_name":"2test_first_name2",
            "last_name":"2test_last_name2",
            "phone":"123456789",
            "credit_cards":[
                {
                    "id":"kkndg6",
                    "default":false,
                    "last_4":"1881",
                    "expiration_date":"12/2020",
                    "expiration_month":"12",
                    "expiration_year":"2020",
                    "token":"kkndg6",
                    "image_url":"https://assets.braintreegateway.com/payment_method_logo/visa.png?environment=sandbox"
                },
                {
                    "id":"6jvmhb",
                    "default":false,
                    "last_4":"1881",
                    "expiration_date":"12/2020",
                    "expiration_month":"12",
                    "expiration_year":"2020",
                    "token":"6jvmhb",
                    "image_url":"https://assets.braintreegateway.com/payment_method_logo/visa.png?environment=sandbox"
                },
                {
                    "id":"kj44cw",
                    "default":true,
                    "last_4":"1881",
                    "expiration_date":"12/2020",
                    "expiration_month":"12",
                    "expiration_year":"2020",
                    "token":"kj44cw",
                    "image_url":"https://assets.braintreegateway.com/payment_method_logo/visa.png?environment=sandbox"
                }
            ]
        }