FORMAT: 1A
HOST: http://52.31.72.139/

# vw2-api

The VW2-API provides a represenation of data handling for [ViewWorld](http://viewworld.net).
We follow the RESTful principles, so the API is stateless and http methods 
and response codes are used whenever possible.

## Sessions [/sessions]

### sessions#create [POST]
Before using the API you have to authenticate yourself with valid ```login``` (name or email) and ```password```.
JSON representation of given user with valid authentication token is returned
if everything goes well. Each subsequent request to different API endpoints has to have
```Authorization``` header with valid token as a value.
Please note that ```token``` in this and all other endpoints is only an example and for
working with the API you have to generate your own valid ```token```.

+ Request (application/json)

        {
            "login": "testuser",
            "password": "testpassword"
        }
        
+ Response 201 (application/json; charset=utf-8)

    + Body
    
            {
                "id": 1,
                "token": "3KeAPOuxtIFCMweJB7qLVA",
                "email": "testuser@viewworld.net",
                "first_name": "Test",
                "last_name": "User"
            }
            
### sessions#destroy [DELETE]
To log out it's necessary to delete current authentication token through this endpoint.

+ Request
    + Headers
    
            Authentication: 3KeAPOuxtIFCMweJB7qLVA

+ Response 204

## Forms Collection [/forms]

### forms#index [GET]
Collection of all availible forms scoped to currently signed in user.
So only forms associated to same Organisation as a User are listed.
> Accessible by: 
> ```Sysadmin```,
> ```Admin```

+ Request
    + Headers
    
            Authentication: 3KeAPOuxtIFCMweJB7qLVA

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "id":12,
                "name":"Species observation",
                "data":[
                    {
                        "id":1,
                        "title":{
                            "en":"What species did you see?"
                        },
                        "type":"text"
                    },
                    {
                        "id":5,
                        "title":{
                            "en":"Number of individuals"
                        },
                        "type":"numeric"
                    },
                    {
                        "id":2,
                        "title":{
                            "en":"Where was the observation made"
                        },
                        "type":"gps"
                    },
                    {
                        "id":9,
                        "title":{
                            "en":"Et billede mere"
                        },
                        "type":"media"
                    },
                    {
                        "id":3,
                        "title":{
                            "en":"Did you get a picture?"
                        },
                        "type":"media"
                    },
                    {
                        "id":4,
                        "title":{
                            "en":"Did you observe alone?"
                        },
                        "type":"yes_no"
                    },
                    {
                        "id":6,
                        "title":{
                            "en":"User"
                        },
                        "type":"metadata"
                    },
                    {
                        "id":7,
                        "title":{
                            "en":"Timestamp"
                        },
                        "type":"metadata"
                    },
                    {
                        "id":8,
                        "title":{
                            "en":"Date/time"
                        },
                        "type":"date_time"
                    }
                ]
            },
            {
                "id":2284,
                "name":"Flowers in the village",
                "data":[
                    {
                        "id":1,
                        "title":{
                            "en":"Describe the flower"
                        },
                        "type":"text"
                    },
                    {
                        "id":6,
                        "title":{
                            "en":"How many different colours does the flower have?"
                        },
                        "type":"numeric"
                    },
                    {
                        "id":2,
                        "title":{
                            "en":"GPS Location"
                        },
                        "type":"gps"
                    },
                    {
                        "id":3,
                        "title":{
                            "en":"In which district?"
                        },
                        "type":"select"
                    },
                    {
                        "id":4,
                        "title":{
                            "en":"Date and Time of observation"
                        },
                        "type":"date_time"
                    },
                    {
                        "id":5,
                        "title":{
                            "en":"Take a picture of the flower"
                        },
                        "type":"media"
                    }
                ]
            },
            {
                "id":1408,
                "name":"Little sun",
                "data":[
                    {
                        "id":2,
                        "title":{
                            "en":"Hvornår blev den solgt"
                        },
                        "type":"date_time"
                    },
                    {
                        "id":1,
                        "title":{
                            "en":"Antal solgte lamper"
                        },
                        "type":"numeric"
                    },
                    {
                        "id":3,
                        "title":{
                            "en":"Hvor er vi?"
                        },
                        "type":"gps"
                    },
                    {
                        "id":4,
                        "title":{
                            "en":"Username"
                        },
                        "type":"metadata"
                    },
                    {
                        "id":5,
                        "title":{
                            "en":"Hvad er dit estimerede lager"
                        },
                        "type":"numeric"
                    },
                    {
                        "id":6,
                        "title":{
                            "en":"Hvordan er den solgt"
                        },
                        "type":"select"
                    },
                    {
                        "id":7,
                        "title":{
                            "en":"If credit down payment"
                        },
                        "type":"numeric"
                    },
                    {
                        "id":8,
                        "title":{
                            "en":"Slutkunde navn"
                        },
                        "type":"text"
                    },
                    {
                        "id":9,
                        "title":{
                            "en":"slutkunde telefon nummer"
                        },
                        "type":"numeric"
                    },
                    {
                        "id":10,
                        "title":{
                            "en":"Date"
                        },
                        "type":"metadata"
                    },
                    {
                        "id":11,
                        "title":{
                            "en":"Billede af modtager"
                        },
                        "type":"media"
                    },
                    {
                        "id":12,
                        "title":{
                            "en":"Stregkode"
                        },
                        "type":"barcode"
                    }
                ]
            }
        ]
        
### forms#create [POST]
You may create your own form using this endpoint.
Form has to be posted as valid JSON with all required data fields.
Returns created form with status ```201```.

+ Request (application/json)
    + Headers
    
            Authentication: 3KeAPOuxtIFCMweJB7qLVA
            
    + Body

            {
                "name":"Demo Species Observations",
                "groups":[
                    1,
                    2,
                    3
                ],
                "active":true,
                "data":[
                    {
                        "id":1,
                        "hint":{
                            "en":"name of species"
                        },
                        "type":"text",
                        "items":{
                        },
                        "title":{
                            "en":"What species did you see?"
                        },
                        "editable":true,
                        "required":true
                    },
                    {
                        "id":2,
                        "hint":{
                            "en":"name of species"
                        },
                        "type":"text",
                        "items":{
                        },
                        "title":{
                            "en":"What species did you see?"
                        },
                        "editable":true,
                        "required":true
                    }
                ],
                "order":[
                    2,
                    1
                ]
            }

+ Response 201 (application/json; charset=utf-8)

            {
                "id":2315,
                "name":"Demo Species Observations",
                "active":true,
                "locked":false,
                "verification":{
                    "required":false,
                    "default":"verified"
                },
                "data":[
                    {
                        "id":1,
                        "hint":{
                            "en":"name of species"
                        },
                        "type":"text",
                        "items":{
                        },
                        "title":{
                            "en":"What species did you see?"
                        },
                        "editable":true,
                        "required":true
                    },
                    {
                        "id":2,
                        "hint":{
                            "en":"name of species"
                        },
                        "type":"text",
                        "items":{
                        },
                        "title":{
                            "en":"What species did you see?"
                        },
                        "editable":true,
                        "required":true
                    }
                ],
                "groups":[
                    {
                        "id":8,
                        "parent_id":1,
                        "name":"Demo HQ"
                    },
                    {
                        "id":1838,
                        "parent_id":8,
                        "name":"qweqwe"
                    },
                    {
                        "id":1928,
                        "parent_id":8,
                        "name":"Collection of animals"
                    },
                    {
                        "id":1929,
                        "parent_id":8,
                        "name":"Niels DEMO group"
                    },
                    {
                        "id":1927,
                        "parent_id":8,
                        "name":"Map constructor presentation"
                    },
                    {
                        "id":142,
                        "parent_id":8,
                        "name":"Country Office"
                    },
                    {
                        "id":1364,
                        "parent_id":8,
                        "name":"Business"
                    },
                    {
                        "id":1815,
                        "parent_id":8,
                        "name":"dev-test-organisation-1.0.0"
                    },
                    {
                        "id":2015,
                        "parent_id":8,
                        "name":"Well inspectors"
                    },
                    {
                        "id":2035,
                        "parent_id":8,
                        "name":"Well inspectors..."
                    },
                    {
                        "id":2016,
                        "parent_id":8,
                        "name":"Vllage Capacity Test"
                    },
                    {
                        "id":1099,
                        "parent_id":142,
                        "name":"Uganda"
                    },
                    {
                        "id":1392,
                        "parent_id":1203,
                        "name":"Kunde"
                    },
                    {
                        "id":1363,
                        "parent_id":1364,
                        "name":"Distribution"
                    },
                    {
                        "id":1203,
                        "parent_id":1364,
                        "name":"Håndværker"
                    },
                    {
                        "id":1818,
                        "parent_id":1815,
                        "name":"dev-organisation-group-1.1.1"
                    },
                    {
                        "id":1817,
                        "parent_id":1815,
                        "name":"dev-test-organisation-1.1.0"
                    },
                    {
                        "id":1819,
                        "parent_id":1815,
                        "name":"dev-organisation-group-1.1.2"
                    },
                    {
                        "id":1822,
                        "parent_id":1817,
                        "name":"dev-test-organisation-1.2.2"
                    },
                    {
                        "id":1821,
                        "parent_id":1817,
                        "name":"dev-test-organisation-1.2.1"
                    }
                ]
            }

## Form [/forms/{form_id}]

+ Parameters
    + form_id:12 (number) - ID of requested form.

### forms#show [GET]
JSON representation of requested form. Objects in data array are ordered according to ```order``` field.
```order``` field is accesible only during ```POST``` and ```PATCH```.
All members of ```groups``` array has optional ```associated``` value.
For users form is visible only if  it has set ```associated: true``` to the same Group as given User.

+ Request
    + Headers
    
            Authentication: 3KeAPOuxtIFCMweJB7qLVA

+ Response 200 (application/json; charset=utf-8)

        {
            "id": 12,
            "name": "Species observation",
            "locked": false,
            "verification": {
                "required": null,
                "default": "submitted"
            },
            "data": [
                {
                    "id": 1,
                    "hint": {
                        "en": ""
                    },
                    "type": "text",
                    "uuid": "dd11e101-4e43-4da7-adae-ad6b977d5dd0",
                    "items": {
                        "type": "string",
                        "required": true
                    },
                    "title": {
                        "en": "What species did you see?"
                    },
                    "editable": true,
                    "required": true,
                    "inputType": "text",
                    "includedInFeed": true
                },
                {
                    "id": 5,
                    "hint": {
                        "en": ""
                    },
                    "type": "numeric",
                    "uuid": "c6ea1a13-47d9-4e9d-b11a-5497fd1b07b0",
                    "items": {
                        "type": "integer",
                        "default": 1,
                        "maximum": 20,
                        "minimum": 0,
                        "required": false,
                        "exclusiveMaximum": true,
                        "exclusiveMinimum": false
                    },
                    "title": {
                        "en": "Number of individuals"
                    },
                    "editable": true,
                    "required": false,
                    "inputType": "textinteger",
                    "includedInFeed": true
                },
                {
                    "id": 2,
                    "hint": {
                        "en": ""
                    },
                    "type": "gps",
                    "uuid": "e427769b-1e3b-4e4f-9c72-2216912b564b",
                    "items": {
                        "type": "array",
                        "required": true
                    },
                    "title": {
                        "en": "Where was the observation made"
                    },
                    "editable": true,
                    "required": true,
                    "inputType": "GPS",
                    "includedInFeed": true
                },
                {
                    "id": 9,
                    "hint": {
                        "en": "Maximum file size is 8Mb."
                    },
                    "type": "media",
                    "uuid": "ddbbf384-b2b0-44c8-af8f-f8cedac6a015",
                    "items": {
                        "type": "object",
                        "required": false,
                        "properties": {
                            "file": {
                                "type": "string",
                                "required": false,
                                "minLength": 1
                            },
                            "size": {
                                "type": "integer",
                                "minimum": 1,
                                "required": false
                            },
                            "assetId": {
                                "type": "integer",
                                "minimum": 1,
                                "required": false
                            }
                        }
                    },
                    "title": {
                        "en": "Et billede mere"
                    },
                    "editable": true,
                    "required": false,
                    "inputType": "uploadImage"
                },
                {
                    "id": 3,
                    "hint": {
                        "en": ""
                    },
                    "type": "media",
                    "uuid": "e230f360-c479-40cb-b167-49e112760d4f",
                    "items": {
                        "type": "object",
                        "required": false,
                        "properties": {
                            "file": {
                                "type": "string",
                                "required": false,
                                "minLength": 1
                            },
                            "size": {
                                "type": "integer",
                                "minimum": 1,
                                "required": false
                            },
                            "assetId": {
                                "type": "integer",
                                "minimum": 1,
                                "required": false
                            }
                        }
                    }
                },
                {
                    "id": 4,
                    "hint": {
                        "en": ""
                    },
                    "type": "yes_no",
                    "uuid": "694d4915-6ce4-4da1-baee-b4e99419c44a",
                    "items": {
                        "type": "boolean",
                        "default": true,
                        "required": false
                    },
                    "title": {
                        "en": "Did you observe alone?"
                    },
                    "editable": true,
                    "required": false,
                    "inputType": "checkbox"
                },
                {
                    "id": 6,
                    "hint": {
                        "en": ""
                    },
                    "type": "metadata",
                    "uuid": "743879e6-3d39-481e-b24b-5e992b263574",
                    "items": {
                        "type": "string",
                        "required": true
                    },
                    "title": {
                        "en": "User"
                    },
                    "editable": false,
                    "required": true,
                    "inputType": "metausername",
                    "includedInFeed": true
                },
                {
                    "id": 7,
                    "hint": {
                      "en": ""
                    },
                    "type": "metadata",
                    "uuid": "2d8d0297-a938-47ed-9188-5c3d1b4d8cfc",
                    "items": {
                        "type": "integer",
                        "required": true
                    },
                    "title": {
                        "en": "Timestamp"
                    },
                    "editable": false,
                    "required": true,
                    "inputType": "metatimestamp",
                    "includedInFeed": true
                },
                {
                    "id": 8,
                    "hint": {
                        "en": "gemt...."
                    },
                    "type": "date_time",
                    "uuid": "bd34f1e6-7237-4fc0-9bfe-6d99916f7269",
                    "items": {
                        "type": "integer",
                        "maximum": "",
                        "minimum": "",
                        "required": false
                    },
                    "title": {
                        "en": "Date/time"
                    },
                    "editable": false,
                    "required": false,
                    "inputType": "datetime"
                }
            ],
            "groups": [
                {
                    "id": 8,
                    "parent_id": 1,
                    "name": "Demo HQ"
                },
                {
                    "id": 1838,
                    "parent_id": 8,
                    "name": "qweqwe"
                },
                {
                    "id": 1928,
                    "parent_id": 8,
                    "name": "Collection of animals",
                    "associated": true
                },
                {
                    "id": 1929,
                    "parent_id": 8,
                    "name": "Niels DEMO group"
                },
                {
                    "id": 1927,
                    "parent_id": 8,
                    "name": "Map constructor presentation"
                },
                {
                    "id": 142,
                    "parent_id": 8,
                    "name": "Country Office"
                },
                {
                    "id": 1364,
                    "parent_id": 8,
                    "name": "Business"
                },
                {
                    "id": 1815,
                    "parent_id": 8,
                    "name": "dev-test-organisation-1.0.0"
                },
                {
                    "id": 2015,
                    "parent_id": 8,
                    "name": "Well inspectors"
                },
                {
                    "id": 2035,
                    "parent_id": 8,
                    "name": "Well inspectors..."
                },
                {
                    "id": 2016,
                    "parent_id": 8,
                    "name": "Vllage Capacity Test"
                },
                {
                    "id": 1099,
                    "parent_id": 142,
                    "name": "Uganda"
                },
                {
                    "id": 1392,
                    "parent_id": 1203,
                    "name": "Kunde"
                },
                {
                    "id": 1363,
                    "parent_id": 1364,
                    "name": "Distribution"
                },
                {
                    "id": 1203,
                    "parent_id": 1364,
                    "name": "Håndværker"
                },
                {
                    "id": 1818,
                    "parent_id": 1815,
                    "name": "dev-organisation-group-1.1.1"
                },
                {
                    "id": 1817,
                    "parent_id": 1815,
                    "name": "dev-test-organisation-1.1.0"
                },
                {
                    "id": 1819,
                    "parent_id": 1815,
                    "name": "dev-organisation-group-1.1.2"
                },
                {
                    "id": 1822,
                    "parent_id": 1817,
                    "name": "dev-test-organisation-1.2.2"
                },
                {
                    "id": 1821,
                    "parent_id": 1817,
                    "name": "dev-test-organisation-1.2.1"
                }
            ]
        }
        

## Reports [/forms/{form_id}/reports]

+ Parameters
    + form_id:12 (number) - ID of form associated with report.
    
### reports#index [GET]

+ Request
    + Headers
    
            Authentication: 3KeAPOuxtIFCMweJB7qLVA

+ Response 200 (application/json; charset=utf-8)


### reports#create [POST]

+ Request (application/json)
    + Headers
    
            Authentication: 3KeAPOuxtIFCMweJB7qLVA
            
    + Body
    
            {
                "data": [
                    {"1": "tiger"},
                    {"2": "lion"}
                ]
            }

+ Response 201 (application/json; charset=utf-8)

            {
                "id": 2,
                "form_id": 2315,
                "data": [
                    {
                        "1": "tiger"
                    },
                    {
                        "2": "lion"
                    }
                ]
            }

## Report [/forms/{form_id}/reports/{report_id}]

+ Parameters
    + form_id:12 (number) - ID of form associated with report.
    + report_id:1 (number) - ID of requested report.
    
### reports#show [GET]

+ Request
    + Headers
    
            Authentication: 3KeAPOuxtIFCMweJB7qLVA

+ Response 200 (application/json; charset=utf-8)

            {
                "id":15,
                "form_id":2318,
                "data":[
                    {
                        "id":1,
                        "hint":{
                            "en":"name of species"
                        },
                        "type":"text",
                        "report":"tiger",
                        "title":{
                            "en":"What species did you see?"
                        },
                        "editable":true,
                        "required":true
                    },
                    {
                        "id":2,
                        "hint":{
                            "en":"name of species"
                        },
                        "type":"text",
                        "report":"true",
                        "title":{
                            "en":"What species did you see?"
                        },
                        "editable":true,
                        "required":true
                    },
                    {
                        "id":3,
                        "hint":{
                            "en":"fileupload"
                        },
                        "type":"media",
                        "report":{
                            "name":"fp.jpg",
                            "content_type":"image/jpeg",
                            "url":"/files/16/original/fp.jpg?1455108639"
                        },
                        "title":{
                            "en":"upload file?"
                        },
                        "editable":true,
                        "required":true
                    }
                ]
            }